# Generated by Django 3.0.3 on 2020-02-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField()),
                ('task_desc', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[(1, 'Monthly'), (2, 'Weekly'), (3, 'Daily')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task')),
            ],
        ),
    ]
